#!/usr/bin/env sh

set -eu

# Re-render man/*.1 from man/*.1.rst. The rendered troff is committed so that
# an installed grokmirror has man pages without needing docutils, which means
# it has to be regenerated by hand whenever a .rst changes -- that is what
# this script is for.
#
# Run it through uv so the docutils version is the locked one. docutils
# changes its troff output between releases (header quoting, the generator
# comment, how inline literals are escaped), so rendering with whatever
# happens to be installed rewrites every page it touches and buries the real
# change. If the diff for a page you did not edit is not empty, somebody
# rendered with a different version; say so in the commit message rather than
# quietly mixing two styles in one tree.

cd "$(dirname "$0")"

for rst in man/*.1.rst; do
    page="${rst%.rst}"
    uv run rst2man "$rst" > "$page"
    echo "$page"
done
